### ISSUE TITLE
Please specify galaxy tool requirements in readme

### ISSUE THREAD

**Issue by happykhan** [phac-nml/irida-plugin-ectyper#1]
Dunno what i need to install to get this to run.

**Comment by kbessonov1984** [comment]
Hello, this is our development version of the ectyper plugin to run E.coli serotyping. To get it installed just place the jar file into irida plugins folder of your IRIDA server instance (e.g. `/etc/irida/plugins`). In Galaxy instance that runs IRIDA compute jobs, install ectyper version 0.8.1 and `concatenate_multiple_datasets` from `artbio` revision `55cf9d9defd1`. Let us know how it goes and if you made it run.
We are currently in midst of releasing a new version of this plugin that will utilize a greater array of features and do QC checks on reports.

**Comment by kbessonov1984** [comment]
@happykhan We've just released a new version of the plugin with Galaxy configuration instructions. Please check out the [Galaxy configuration section](https://github.com/phac-nml/irida-plugin-ectyper/#galaxy-configuration).
